## Denkst Du Defensiv Danken Dir Das Da Draußen Die Dudes.

Alternativer Titel: *Being a Cunt about Counts*


```{r, eval = FALSE}
# Transform numeric to integer
count_them <- function(supposedly_a_count) {
  
  # Start with assertions and meaningful messages.
  collection_assertions <- makeAssertCollection()
  if (checkmate::anyInfinite(supposedly_a_count)) {
    collection_assertions$push("Input has to be at least countable finite.")
    }
  if (checkmate::anyMissing(supposedly_a_count)) {
    collection_assertions$push("Input is missing.")
  }
  if (!checkmate::testNumeric(supposedly_a_count, lower = 0)) {
    collection_assertions$push("Input has to be only numeric and positive.")
    }
  if (!checkmate::test_number(supposedly_a_count)) {
    collection_assertions$push("Input has to have length one.")
    }
  reportAssertions(collection = collection_assertions)
  
   if (!checkmate::test_count(supposedly_a_count)) {
          warning(
            "rounding ", supposedly_a_count,
            " to the nearest integer."
    )
    supposedly_a_count <- round(supposedly_a_count)
  }
  
  # If variable is not already a intereger.
  supposedly_a_count <- as.integer(supposedly_a_count)
}
```
Wirkt harmlos und unscheinbar, oder? Zweck der effektiv drei Befehle hier drüber ist es, `supposedly_a_count` gegebenenfalls (mit einer Warnung) zu 
einer Zählvariable, also einer nicht-negativen ganzen Zahl, zu runden
so dass man sich im Folgenden darauf verlassen kann dass `supposedly_a_count` eben tatsächlich
eine sinnvolle *Anzahl*  von irgendwas repräsentiert. 

a) Identifizieren Sie möglichst viele der hier getroffenen *impliziten* Annahmen über das Objekt `supposedly_a_count`. (Am besten: *bevor* Sie sich die entsprechenden Tests im mitgelieferten Testfile anschauen.)
-numerische Werte
- endlich abzaehlbar (kein Inf) und numerisch
- kein NA
- Input Länge scheinbar nur eins, sonst wird "does the right thing for sensible inputs" nicht gepassed, aber "does the right thing for problematic inputs" schon

b) Modifizieren Sie den Code so dass alle diese impliziten Annahmen mittels *expliziten* `assertions` überprüft werden, so dass immer entweder eine informative Fehlermeldung oder ein korrektes/vernünftiges Ergebnis (evtl. mit entsprechenden Warnmeldungen, s.o.) zurückgegeben wird.
